all:
	# gradle runLeet -Pargs="['-u', 'myuser', 'some other argument', 'and/a/path']"
	gradle runLeet -Pargs="001:tests/leet001"
001:
	gradle runLeet -Pargs="001:tests/leet001"
003:
	gradle runLeet -Pargs="003:tests/leet003"
