import cn.mzen.common.*;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openjdk.jmh.annotations.Benchmark;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final Logger logger = LogManager.getLogger(App.class);
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args){
        logger.info("app");
        ListNode node=new ListNode(1);
        logger.info(node);
        App.testConcatenatingStrings();
    }

    @Benchmark
    public static void testConcatenatingStrings() {

        String x = "", y = "", z = "";

        for (int i = 0; i < 100; i++) {
            x += i; y += i; z += i;

            logger.debug("Concatenating strings " + x + y + z);
        }
    }
}
