import cn.mzen.common.*;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openjdk.jmh.annotations.Benchmark;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final Logger logger = LogManager.getLogger(App.class);
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args){
        if(args.length<2) {
            logger.error("Need 2 parameter：");
            logger.error("1> is the working directory, which have all test cases file.");
            logger.error("2> is test cases number, such as 001.");
            return;
        }else{
            logger.info(args.length);
            CaseLoader loader = new CaseLoader();
        }
        // String casePath = args[0];
        // logger.info(casePath);
        // logger.info(args[1]);
    }

    @Benchmark
    public static void testConcatenatingStrings() {
        String x = "", y = "", z = "";

        for (int i = 0; i < 100; i++) {
            x += i; y += i; z += i;

            logger.debug("Concatenating strings " + x + y + z);
        }
    }
}
