import cn.mzen.common.*;
import cn.mzen.deepj.basic.ClassInstance;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final Logger logger = LogManager.getLogger(App.class);
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args){
        ClassInstance.RunEqual();
        String valie = "abcd";
        logger.info("app");
        ListNode node=new ListNode(1);
        logger.info(node);
    }
}
