all:
	gradle clean build
leetcode:
	gradle :leetcode:runLeet
clean:
	gradle clean
runleetcode:
	java -jar ./leetcode/build/libs/bugfree-module-leetcode-0.0.1-SNAPSHOT.jar

leet001:
	gradle :leetcode:runLeet -Pcase="001"
